### ISSUE TITLE
VideoCallEscalationQueue Import Error

### ISSUE THREAD

**Issue by RDurkin-GitHub** [amazon-connect/video-call-escalation#12]
Hi

When trying to import the VideoCallEscalationQueue Contact Flow, it fails to import.

It just keeps saying that the file can't be read.
No issue importing the VideoCallEscalationChat Contact Flow

**Comment by lwarneminde** [comment]
This error will appear if you try to import the flow into a standard contact flow rather than into a customer queue flow.
In the contact flow screen, click the drop-down button next to Create contact flow, and select Create customer queue flow, then try importing the flow file.

**Comment by RDurkin-GitHub** [comment]
Perfect, that has worked
