### ISSUE TITLE
the VideoCallEscalationQueue is not getting imported

### ISSUE THREAD

**Issue by aartikal** [amazon-connect/video-call-escalation#17]
![image](https://user-images.githubusercontent.com/110903158/183631551-9f53ecf4-4094-48ab-a070-6c8194db6187.png)

**Comment by virtualgill** [comment]
Hi @aartikal, please verify if you are creating the correct type of queue outlined in the instructions. For _VideoCallEscalationQueue_ you need to create a **customer queue flow** (use the dropdown on the create contact flow button to choose that option). For _VideoCallEscalationChat_ just use the standard contact flow.

**Comment by davelemons** [comment]
Closing out older issues, please re-open if the advice above didn't address the issue.
